import '@/assets/scss/style.scss';
import AppProvidersWrapper from '@/components/wrapper/AppProvidersWrapper';
import { DEFAULT_PAGE_TITLE } from '@/context/constants';
import { Roboto } from 'next/font/google';
const roboto = Roboto({
  display: 'swap',
  style: ['normal', 'italic'],
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900']
});
export const metadata = {
  title: {
    template: '%s | Taplox - Responsive Admin Dashboard Template',
    default: DEFAULT_PAGE_TITLE
  },
  description: 'Generated by create next app'
};
export default function RootLayout({
  children
}) {
  return <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" />
      </head>
      <body className={roboto.className}>
        <div id="__next_splash">
          <AppProvidersWrapper>{children}</AppProvidersWrapper>
        </div>
      </body>
    </html>;
}